### ISSUE TITLE
Unknown Error Occurred 

### ISSUE THREAD

**Issue by avidnumberer** [Danielhiversen/home_assistant_adax_local#5]
Can’t setup a local heater. Using latest version of Home Assistant OS on a rPi4. Have tried with built in bluetooth and with a dongle. Can’t get past the wifi details screen.

File "/usr/src/homeassistant/homeassistant/components/adax/config_flow.py", line 78, in async_step_local
    device_configured = await configurator.configure_device()
  File "/usr/local/lib/python3.10/site-packages/adax_local/__init__.py", line 141, in configure_device
    device, self._mac_id = await scan_for_available_ble_device()
  File "/usr/local/lib/python3.10/site-packages/adax_local/__init__.py", line 186, in scan_for_available_ble_device
    discovered = await bleak.discover(timeout=60)
TypeError: discover() got an unexpected keyword argument 'timeout'

**Comment by sjabby** [comment]
Same error here, tried a few dongles and BT on RPI3:

```
2022-10-30 23:14:23.313 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/adax/config_flow.py", line 78, in async_step_local
    device_configured = await configurator.configure_device()
  File "/usr/local/lib/python3.10/site-packages/adax_local/__init__.py", line 141, in configure_device
    device, self._mac_id = await scan_for_available_ble_device()
  File "/usr/local/lib/python3.10/site-packages/adax_local/__init__.py", line 186, in scan_for_available_ble_device
    discovered = await bleak.discover(timeout=60)
TypeError: discover() got an unexpected keyword argument 'timeout'

```
